title: <p align="center"> Rajaram Karanth </p>
logo: /assets/img/Rajaram.JPG

description:
  <p align="center">
  #<a href="pdf/resume.pdf">Resume</a> |
  <a href="www.linkedin.com/in/rajaramkaranth">LinkedIn</a> |
  <a href="https://github.com/RajaramKaranth">GitHub</a>
  
  <br>   
  Pursuing EPGP program in AI & ML offered by IIIT Bangalore and UpGrad.
  Working in Wipro lab45 on projects bringing AI to business problems across industry domains.
  Have led multitude of client engagements ranging from AI enabled business Transformations, large IT Managed Services, Greenfied programs in my career with IBM and Wipro.
  Have performed leadership roles in client engagements and at organization levels.
  <br>
  </p>



theme: jekyll-theme-minimal
